const estateData = {
    estates: [
        {
            title: 'Hazey Craters',
            location: 'Dark Side of the Moon',
            description: 'Explore infamous craters on the dark side of the moon',
            price: 500000,
            image: '/images/HazeyCraters.jpg',
            status: false,
        },
        {
            title: 'Strawberry Moon Condos',
            location: 'Nubium',
            description: 'Enjoy Breathtaking views from futuristic condos',
            price: 450000,
            image: 'https://i.pinimg.com/originals/84/5b/ec/845bec51d09688387f289e33dc9e0f76.jpg',
            status: false,
        },
        {
            title: 'Mystic Crator',
            location: 'Nectaris',
            description: 'Explore the mystical crators in the wonderous location of Nectaris',
            price: 350000,
            image: 'https://images.hdqwalls.com/wallpapers/astronaut-space-digital-art-fantasy-vv.jpg',
            status: false,
        },
        {
            title: 'Saturn Sunset',
            location: 'Lunä',
            description: 'Adventurous walks along a sunset from Saturn',
            price: 720000,
            image: '/images/saturnSunsets.jpg',
            status: false,
        },
        {
            title: 'MoonRock Peaks',
            location: 'Tranquillitatis',
            description: 'Feel the tranquill nature among the highest peaks in the galaxy',
            price: 680000,
            image: 'https://wallpaperforu.com/wp-content/uploads/2021/01/fantasy-wallpaper-21010121275747-scaled.jpg',
            status: false,
        },
        {
            title: 'Lunar City',
            location: 'Palus',
            description: 'Take in the lively city at the heart of the Moon',
            price: 700000,
            image: 'https://i.pinimg.com/originals/e1/aa/9e/e1aa9efe9c53f201f59b372467d1dfb5.jpg',
            status: true,
        },
        {
            title: 'Neon Pod',
            location: 'Procellarum',
            description: 'Be apart of the city in a modest but cozy futuristic pod',
            price: 20000,
            image: 'https://w0.peakpx.com/wallpaper/1023/756/HD-wallpaper-aenami-women-futuristic-city-science-fiction-spaceship-digital-art-meteorite-stars.jpg',
            status: false,
        },
        {
            title: 'Pyramid Scapes',
            location: 'Serenitatis',
            description: 'Break free from the hustle and bustle, making your escape, Pyramid Scapes',
            price: 400750,
            image: 'https://c4.wallpaperflare.com/wallpaper/365/890/437/fantasy-city-moon-pyramid-pyramidship-wallpaper-preview.jpg',
            status: true,
        },
        {
            title: 'Aurora Heights',
            location: 'Imbrium',
            description: 'Working and living in the city of Imbrium will be just as comfortable in Aurora Heights',
            price: 350000,
            image: 'https://cdn.pixabay.com/photo/2020/06/20/04/33/space-5319624_1280.jpg',
            status: false,
        },
        {
            title: 'Polar Place',
            location: 'Cognitum',
            description: 'Get to know the coolest place on the moon',
            price: 50500,
            image: 'https://i.pinimg.com/564x/97/1e/08/971e08b419657132368c0a86740c0be2.jpg',
            status: false,
        },

    ],
};

module.exports = estateData;